source: _src
destination: docs

timezone: Europe/Berlin
encoding: UTF-8

title: Simple contract
description: ""
url: "https://simple_contracts.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
